production:
  solr:
    solr:
    hostname: localhost
    port: 8983
    solr_jar: solr/solr-4.2.0/example/start.jar
    log_level: WARNING
    max_memory: 3G
    read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    solr_jar: solr/solr-4.2.0/example/start.jar
    log_level: INFO
    max_memory: 3G

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
